SepaCountries = {
    # euro sepa countries
    "AT": "Austria",
    "BE": "Belgium",
    "CY": "Cyprus",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GR": "Greece",
    "IE": "Ireland",
    "IT": "Italy",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MT": "Malta",
    "MC": "Monaco",
    "NL": "Netherlands",
    "PT": "Portugal",
    "SM": "San Marino",
    "SK": "Slovakia",
    "SV": "Slovenia",
    "ES": "Spain",
    # non euro SEPA conuntries
    "BG": "Bulgaria",
    "HR": "Croatia",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "HU": "Hungary",
    "IS": "Iceland",
    "LI": "Liechtenstein",
    "NO": "Norway",
    "PL": "Poland",
    "RO": "Romania",
    "SE": "Sweden",
    "CH": "Switzerland",
    "GB": "Great Britain"
}
